### ISSUE TITLE
Errors in example code

### ISSUE THREAD

**Issue by apowers313** [worldline/swagger-jack#24]
I'm trying to get swagger-jack up and running for the first time, so I cut and paste the code from the readme.md ("import and configure the two middlewares") into a .js file and then ran the .js. After fixing a few errors with missing commas and missing braces, I get the error: "Error: responseClass is mandatory. If no result expected, responseClass should be void"

I'm assuming that this is complaining about a malformed swagger description, but I'm not educated enough about swagger to know what responseClass it is looking for. Can you give me a hint about how I can fix this?

**Comment by feugy** [comment]
Sorry for the misleading code.
In the `api.apis` part of the `swagger.generator` function, you need to define what will be your API response: the famous `reponseClass`. 

This is how the Swagger specification [works](https://github.com/wordnik/swagger-core/wiki/Api-Declaration) : you must provide a schema defining what properties are in the API response (see [the spec for data-types](https://github.com/wordnik/swagger-core/wiki/Datatypes))
This schema is referenced in the `api.models` part of your descriptor, and is a valid [json-schema](http://json-schema.org/).

Here an example inspired from the [tests](/worldline/swagger-jack/blob/master/test/fixtures/addressApi.yml) :

``` javascript
app.use(swagger.generator(app, {
      // general descriptor part
      apiVersion: '2.0',
      basePath: 'http://my-hostname.com/api'
    }, [{
    api: {
      resourcePath: '/apis', 
      apis: [{
        path: '/address',
        operations: [{
           httpMethod: 'POST',
           nickname: 'createAddress',
           responseClass: 'Address'
           parameters: {
             dataType: 'Address'
             paramType: 'body',
             required: true
           }
        }],
        models: {
          Address: {
            id: 'Address'
            properties: {
              zipcode: {type: 'long'},
              street: { type: 'string'},
              city: {type: 'string'}
            }
          }
       }]
       controller: {
          createAdress: (addr) {
            // save in db
            return addr;
          }
    });
```

(I suggest you to split the `api`part into a separate Yaml file, and the `controller` into a separate Js file).

Unfortunatly, I discovered that the Swagger specification has changed since we implemented Swagger-jack. Some attributes were renamed : `responseClass` is now `responseMessage.responseModel`, `httpOperation` is now `operation`... We'll update as soon as possible.
